const mongoose = require('mongoose');

const settingSchema = new mongoose.Schema({
    currency: {
        name: { type: String, default: 'Indian Rupee' },
        symbol: { type: String, default: '₹' },
        countryCode: { type: String, default: 'IN' },
        currencyCode: { type: String, default: 'INR' },
        isDefault: { type: Boolean, default: true },
    },
    isGooglePlayEnabled: { type: Boolean, default: true },
    isStripeEnabled: { type: Boolean, default: false },
    stripePublishableKey: { type: String, default: '' },
    stripeSecretKey: { type: String, default: '' },
    isRazorpayEnabled: { type: Boolean, default: false },
    razorPayId: { type: String, default: '' },
    razorSecretKey: { type: String, default: '' },
    isFlutterwaveEnabled: { type: Boolean, default: false },
    flutterWaveId: { type: String, default: '' },
    privacyPolicyLink: { type: String, default: '' },
    termsOfUsePolicyLink: { type: String, default: '' },
    isDummyData: { type: Boolean, default: false },
    loginBonus: { type: Number, default: 100 },
    privateCallRate: { type: Number, default: 20 },
    durationOfShorts: { type: Number, default: 30 },
    minCoinsToCashOut: { type: Number, default: 500 },
    minCoinsForPayout: { type: Number, default: 1000 },
    pkEndTime: { type: Number, default: 60 },
    videoBanned: [{ type: String }],
    postBanned: [{ type: String }],
    sightengineUser: { type: String, default: '' },
    sightengineApiSecret: { type: String, default: '' },
    shortsEffectEnabled: { type: Boolean, default: false },
    androidEffectLicenseKey: { type: String, default: '' },
    iosEffectLicenseKey: { type: String, default: '' },
    watermarkEnabled: { type: Boolean, default: false },
    watermarkIcon: { type: String, default: '' },
    privateKey: {
        type: { type: String, default: '' },
        project_id: { type: String, default: '' },
        private_key_id: { type: String, default: '' },
        private_key: { type: String, default: '' },
        client_email: { type: String, default: '' },
        client_id: { type: String, default: '' },
        auth_uri: { type: String, default: '' },
        token_uri: { type: String, default: '' },
        auth_provider_x509_cert_url: { type: String, default: '' },
        client_x509_cert_url: { type: String, default: '' },
        universe_domain: { type: String, default: '' },
    },
    profilePhotoList: [{ type: String }],
}, { timestamps: true });

module.exports = mongoose.model('Setting', settingSchema);
